### PR TITLE
Fix possible errors when encoding/decoding guns

### PR DESCRIPTION
**Pull request by juanmuscaria**

### CODE REVIEW

**Comment by josephtarbit** [comment]
Why is this necessary?

**Comment by josephtarbit** [comment]
(There will always be a magazine present)

**Comment by juanmuscaria** [comment]
During decoding, if it was previously encoded with `writeAll` false, the magazine stack will be an empty stack, throwing an error during decode. The ammo provider by default is also initialized with an empty stack, so I'm also covering the case it may also be encoded with an empty stack.

**Comment by josephtarbit** [comment]
The no-args constructer (where the magazine stack is set to empty) should only ever be used on the client. On an initial sync (where writeAll is set to true) the magazine is set so there should never be a situation where the magazine stack is null, if there is then that is a bug.

**Pull request merged**
