### PR TITLE
Shooting improvements

### LINKED ISSUE #16: Some hits from guns do not register.
As you can see in the video below, on the last zombie I killed, 6 total shots were fired but only 3 of those 6 registered as hits and did damage. It seems to be happening on every gun but I haven't tested each individually.

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-06-28.zip](https://github.com/nexusnode/crafting-dead/files/5527469/2020-11-11.19-06-28.zip)

This is also tested only on Zombies as seen in the video, not sure if it applies to players but still worth looking into and fixing :)

### PR DESCRIPTION
**Pull request by Afarion1**
1. Validation checks for blocks.
2. Validation is now based on a hit vector that is sent by a client. I tested it a lot and now hit registration is much better.
The highest difference between positions of a shot entity on the client-side and in the validation was about 0.06 blocks. The difference might be larger in case of a running player, while I tested it on a running sheep.
If this precision of the validation will turn out to be not good enough, I think that it could be further improved by keeping track of client-side interpolation and compensating it in the validation.
3. Trigger packets are desynced with validation packets and it was hindering high fire rate hit registration. I removed trigger check on the validation because I don't think it provides anything. 
4. Fixed double kill feed notification/sound on high fire rates.

closes #16 

P.S. Not sure why the diff of 2 files can't be calculated, but I'm pretty sure I've listed everything I had changed.

### CODE REVIEW

**Comment by josephtarbit** [comment]
The reason it checks for the trigger pressed during validation is because if you run out of ammo or you can’t shoot for some other reason then you could still send hit validation packets and kill people.

**Comment by josephtarbit** [comment]
What do you mean by “Trigger packets are desynced with validation packets”?

**Comment by josephtarbit** [comment]
Also, can't hackers cheat by changing the hit vector sent in the validation packet?

**Comment by Afarion1** [comment]
If I recall correctly, hits on the client don't send packets instantly, but cache or something. Because of that, the trigger packet which sets trigger state to false arrives before hit validation packet does, sometimes.

**Comment by Afarion1** [comment]
Even if we manage to implement good tracking of the look vector (which I very very doubt), the hackers will just change it before sending packets.

**Comment by Afarion1** [comment]
> The reason it checks for the trigger pressed during validation is because if you run out of ammo or you can’t shoot for some other reason then you could still send hit validation packets and kill people.
OK, I will look into it tomorrow

**Comment by josephtarbit** [comment]
> Even if we manage to implement good tracking of the look vector (which I very very doubt), the hackers will just change it before sending packets.

It's very difficult to spoof the rotation/position packet as it only allows small changes per packet.

**Comment by josephtarbit** [comment]
Also I've realised the reason the snapshot system works awfully at the moment, it's because it takes snapshots per world time which is measured in seconds, not tick, therefore the position of a player can change within the time of one snapshot.

**Comment by Afarion1** [comment]
Well, then let's see how look vector based approach works after fixing the snapshot system

**Comment by josephtarbit** [comment]
Fixed in df4762b

**Pull request closed without merging**
